{stdenv, fetchFromGitHub, cmake, log4cpp, libevdev, libusb1 }:

stdenv.mkDerivation (finalAttrs: {
	pname = "g13";
	version = "1.0.4";

	src = fetchFromGitHub {
		owner = "khampf";
		repo = "g13";
		tag = "v${finalAttrs.version}";
		hash = "sha256-tF9A0fdbooMbLzquHrCWkQulFI1lL8H3jkqQvd8zZJs=";
	};

	# This is a patch generated by claude because a change to a newer version of gcc
	# does not transitively pull a missing library (<algorithm>) from another
	# included library any more
	postPatch = "sed -i '1i #include <algorithm>' g13_stick.cpp"; 

	nativeBuildInputs = [ cmake ];

	buildInputs = [
		log4cpp
		libevdev
		libusb1
	];

	buildFlags = [ "g13d" "pbm2lpbm" ]; #This is to skip building runtests

	cmakeBuildType = "Debug";
	
	# There was no install instructions in g13's CMakeList.txt so this just
	# moves the two build targets into a bin directory in the nix store
	# this also moves the udev rule from the source code into a place where
	# services.udev.packages can install it
	installPhase = ''
		runHook perInstall
		install -Dm755 g13d			$out/bin/g13d
		install -Dm755 pbm2lpbm			$out/bin/pbm2lpbm
		install -Dm644 $src/91-g13.rules	$out/lib/udev/rules.d/91-g13.rules
		runHook postInstall
	'';
})	
