stickzone del STICK_PAGEUP
stickzone del STICK_PAGEDOWN
stickzone bounds STICK_UP 0 0 1 0.3
stickzone bounds STICK_DOWN 0 0.7 1 1
bind G8 1
bind G9 2
bind G10 3
bind G11 4
bind G12 5
bind G13 6
bind G14 7
bind G1 F1
bind G2 F2
bind G3 F3
bind G4 F4
bind G5 F5
bind G6 F6
bind G7 F7
bind LEFT SPACE
bind DOWN LEFTSHIFT
bind G20 B
bind G21 M
bind G22 G
bind G15 LEFTCTRL+LEFTSHIFT+Z
bind G16 LEFTCTRL+LEFTSHIFT+X
bind G17 LEFTCTRL+LEFTSHIFT+C
bind G18 LEFTCTRL+LEFTSHIFT+V
bind G19 LEFTCTRL+LEFTSHIFT+B
